### PR TITLE
Easier switching between keyboards

### PR DESCRIPTION
**Pull request by drop0x55**
Change "require" to wanted keyboard language in top of keybow.lua.

### CODE REVIEW

**Comment by drop0x55** [comment]
@Gadgetoid : I think this would do it. Ref. your latest comment in #62 .

**Comment by drop0x55** [comment]
Maybe putting the layout files in a separate folder is a good idea? Maybe call it "keyboards" So that the require would be "keyboards/english". Less clutter. Sorry for creating a pull request on the master branch. I probably shouldn't have done that. I'm a git noob, so some things are still a little confusing.

**Comment by Gadgetoid** [comment]
Thank you!

PR is fine! I'd rather 100 git noobs tried to contribute than nobody at all! You've got to start somewhere.

For future reference: You can update an existing branch on your repository- if it's part of a pull-request then the associated pull-request will be updated to reflect the new changes.

Always happy to help with pointers about Git/GitHub where I can. I'm an advanced amataur 😆 

A `keyboards` subdirectory is a great idea, keeps everything tidy.

**Comment by drop0x55** [comment]
Btw, I realised now that what I did was exactly your comment in #62. I got so eager I didn't read all of it before I did this. If I had, I would have seen the part about the keyboard folder as well.

**Comment by Gadgetoid** [comment]
Haha! I figured as much and was keeping quiet about that. I shall humbly submit that Great Minds Think Alike.

Did you want to try adding a PR to move things into a `keyboards` or similar directory? Alternatively I can merge and shunt them over.

**Comment by drop0x55** [comment]
I agree!
No, you can do it, it's fine. I won't be in front of a computer until Monday and I'm just happy to have done a PR!

**Comment by AHallqvist** [comment]
I started trying to make a keyboard layout for Swedish, from the norwegian as a start. But I have issues with <> instead sending '*. Maybe drop0x55 could shed some light on how norwegian and/or danish compares to swedish in that?

**Pull request merged**
