### PR TITLE
Mouse movement support

### PR DESCRIPTION
**Pull request by gregprosser**
- add the USB HID description of a mouse
- add the ability to generate a HID report for a mouse (from above)
  - this includes buttons as well as movement
- add lua support for 'clicking' buttons
- expose lua functions to layouts/ code

This implements #48

I've had to manually munge the formatting here since my vim was using tabs, so please run a test build! (I will too)

### CODE REVIEW

**Comment by gregprosser** [comment]
I run this locally and implemented some lua to toggle holding down my right mouse button for a game I play.  Seems to work well.

**Comment by Gadgetoid** [comment]
This is a great addition, thankyou! - sorry I haven't had time to test & merge it yet; the world has been a little chaos lately.

It looks like there's a groundswell of things I need to address with Keybow- I'll hopefully get an opportunity to sprint this in July.

**Comment by jdimpson** [comment]
Hi! I'm trying to understand whether this merge is part of the latest (0.0.4) release, and if so, how to activate it. When I look at the output of dmesg (on the Linux system that I have this plugged into) I see Pimoroni Keybow Keyboard and Pimoroni Keybow Consumer Control show up, as well as a cdc_acm tty USB device. 

I am able to run my own lua code for my custom button layout, but none of the mouse movement commands seem to work. Not sure if this is because my code has errors / misunderstandings, or if the mouse gadget is missing or disabled.

xinput also shows the pimoronic keyboard as a Virtual core keyboard, but does not show anything similar under Virtual core pointer. So I'm guessing I don't have it or don't have it turned on.

**Comment by Gadgetoid** [comment]
These changes aren't in a release yet. If you need a compiled, binary `keybow` then you can grab it from - https://github.com/pimoroni/keybow-firmware/pull/79

You should grab that branch and take `keybow` from the sdcard directory, you'll also find the basic mouse example there.

**Comment by jdimpson** [comment]
Thanks! Just last night I figured out how to build my own, and both the mouse example and my own code worked!

Would you be interested if I updated the README and the make.sh script to better document how to build the project? I've never done a pull request before, so bear with me, but I do understand the idea, and would be interested in helping out.

**Pull request merged**
