### PR TITLE
Bump dependency versions

### PR DESCRIPTION
**Pull request by Gadgetoid**
bcm2835-1.58 -> bcm2835-1.68
lua-5.3.5 -> lua-5.4.0

### CODE REVIEW

**Comment by Blindpete** [comment]
Any idea if this will ever get merged?

**Comment by Gadgetoid** [comment]
Any reason you need it? I can't recall if it actually works! Looks like this was circa my tinkering with the firmware to prep a generally updated release. All the good stuff is in the kernel/system files.

**Comment by Blindpete** [comment]
I've been having issues with hanging so need to reset the Pi, I was hoping a version update my fixed the issues. I've not put any time to working what's going on yet.

**Comment by eXsoR65** [comment]
@Blindpete I found an issue were it crash when my computer reboots. See issue [https://github.com/pimoroni/keybow-firmware/issues/36]()

**Comment by theboyknowsclass** [comment]
i'm having issues with my Pi4 (bcm2835_init: gpio mmap failed: Cannot allocate memory) which I believe is fixed with this?

**Pull request merged**
